[package]
name = "rust-px4-usr-drv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.9"
thiserror = "1"
anyhow = "1"